# Generated by Django 3.0.14 on 2022-10-25 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0002_auto_20221020_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Пост о путешествии', 'verbose_name_plural': 'Посты о путешествии'},
        ),
        migrations.AddField(
            model_name='travel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
