# Generated by Django 4.2.6 on 2023-11-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_country_alter_profile_avatar_travel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='place',
        ),
    ]
