# Generated by Django 4.2.6 on 2023-11-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
