# Generated by Django 3.0.14 on 2022-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='end_of_the_trip',
            field=models.DateField(verbose_name='Дата окончания путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_of_the_trip',
            field=models.DateField(verbose_name='Дата начала путешествия'),
        ),
    ]
