# Generated by Django 3.0.14 on 2022-10-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20221017_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.Category', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='content',
            field=models.TextField(blank=True, verbose_name='Тесет поста'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='end_of_the_trip',
            field=models.DateTimeField(verbose_name='Время окончания путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='expense',
            field=models.CharField(max_length=255, verbose_name='Затраченные средства'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован?'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Место петешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_of_the_trip',
            field=models.DateTimeField(verbose_name='Время начала путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования поста'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок поста'),
        ),
    ]
