# Generated by Django 3.0.14 on 2022-10-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20221017_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.Category', verbose_name='Категория поста'),
        ),
    ]
